version: '3.7'

services:
  postgres:
    container_name: daisy_pg
    image: postgres
    environment:
      POSTGRES_USER: daisy_user
      POSTGRES_PASSWORD: daisy_pass
      POSTGRES_DB: daisy_db
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  bot:
    container_name: daisy_bot
    build: .
    env_file:
      - ./.env
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    container_name: daisy_redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    ports:
      - '6370:6379'
    volumes:
      - ./redis-db:/bitnami/redis/data
    restart: unless-stopped
